name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Jalankan setiap hari pada tengah malam
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v3

      - name: Create 'dist' directory
        run: mkdir -p dist  # Buat direktori dist jika belum ada

      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}  # Menggunakan username dari repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Gunakan GitHub token untuk autentikasi

      - name: List files in current directory (debugging)
        run: ls -l  # List all files di direktori root proyek

      - name: Move output files to 'dist' directory
        run: mv *.svg dist/  # Pindahkan file output ke direktori dist

      - name: List files in 'dist' directory (debugging)
        run: ls -l dist/  # List files di dalam direktori dist untuk memverifikasi file yang ada

      - name: Push Snake Animation to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist  # Tentukan direktori dist sebagai build_dir
          commit_message: Update snake animations
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Gunakan default GITHUB_TOKEN untuk autentikasi
