name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v3

      - name: Create 'dist' directory
        run: mkdir -p dist  # Buat direktori dist jika belum ada

      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}  # Pastikan nama pengguna benar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Gunakan token GitHub

      - name: List current directory (debugging)
        run: ls -la  # List semua file di direktori saat ini untuk debugging

      - name: Move output files to 'dist' directory
        run: mv *.svg dist/ || echo "No SVG files found"  # Pindahkan file, tapi jika tidak ada, tampilkan pesan

      - name: List 'dist' directory (debugging)
        run: ls -la dist/  # Periksa isi direktori dist setelah file dipindahkan

      - name: Push Snake Animation to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
          commit_message: Update snake animations
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Gunakan token untuk autentikasi
