name: Generate Snake Game from GitHub Contributions

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *" # Menjalankan setiap hari
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Generate Snake Game from GitHub Contributions
        uses: Platane/snk@master
        with:
          github_user_name: ${{ github.repository_owner }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
